name: Windows-RDP-LocalX
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download LocalXpose
        run: |
          Invoke-WebRequest https://localxpose.io/ext/loclx-windows-amd64.zip -OutFile loclx.zip
          Expand-Archive loclx.zip
      - name: Authenticate & Start RDP
        run: |
          ./loclx/loclx.exe account login ${{ secrets.LOCALXPOSE_AUTH_TOKEN }}
          Start-Process ./loclx/loclx.exe -ArgumentList "tunnel tcp --port 3389"
          echo "RDP is ready!"
        shell: pwsh
